<?php

return [
    'maximum_ability_history',
    'minimum_ability_history',
    'maximum_trials_attempt',
    'question_generator_n',
    'repeated_rate',
    'question_difficulty_level1',
    'question_difficulty_level2',
    'question_difficulty_level3',
    'question_difficulty_level4',
    'question_difficulty_level5',
    'question_difficulty_easy',
    'question_difficulty_medium',
    'question_difficulty_hard',
    'default_second_per_question',
    'struggling_color',
    'beginning_color',
    'approaching_color',
    'proficient_color',
    'advanced_color',
    'incomplete_color',
    'struggling',
    'beginning',
    'approaching',
    'proficient',
    'advanced',
    'passing_score_percentage',
    'passing_score_accuracy',
    'question_correct_color',
    'question_incorrect_color',
    'pass_ability_level',
    'pass_only_and_or',
    'pass_accuracy_level',
    'no_of_questions_per_learning_skills',
    'max_no_of_question_per_learning_skill',
    'min_no_question_per_learning_objectives',
    'max_no_question_per_learning_objectives',
    'accomplished_objective',
    'not_accomplished_objective',
    'difficulty_selection_type',
    'assignment_credit_points_for_submission_on_time',
    'self_learning_credit_points_for_exercise',
    'self_learning_credit_points_for_test',
    'assignment_starting_accuracy_to_earn_credit_points',
    'assignment_credit_points_earned_for_starting_accuracy',
    'assignment_accuracy_number_of_stages_to_earn_extra_credit_point',
    'assignment_difference_of_accuracy_between_stages',
    'assignment_accuracy_extra_credit_points_for_each_stage',
    'assignment_starting_normalized_ability_to_earn_credit_points',
    'assignment_credit_points_earned_for_starting_normalized_ability',
    'assignment_ability_number_of_stages_to_earn_extra_credit_point',
    'assignment_difference_of_normalized_ability_between_stages',
    'assignment_ability_extra_credit_points_for_each_stage',
    'self_learning_exercise_starting_accuracy_to_earn_credit_points',
    'self_learning_exercise_credit_points_earned_for_starting_accuracy',
    'self_learning_exercise_number_of_stages_to_earn_extra_credit_point',
    'self_learning_exercise_difference_of_accuracy_between_stages',
    'self_learning_exercise_accuracy_extra_credit_points_for_each_stage',
    'self_learning_exercise_starting_normalized_ability_to_earn_credit_points',
    'self_learning_exercise_credit_points_earned_for_starting_normalized_ability',
    'self_learning_exercise_number_of_stages_to_earn_extra_credit_points',
    'self_learning_exercise_difference_of_normalized_ability_between_stages',
    'self_learning_exercise_ability_extra_credit_points_for_each_stage',
    'self_learning_test_starting_accuracy_to_earn_credit_points',
    'self_learning_test_credit_points_earned_for_starting_accuracy',
    'self_learning_test_number_of_stages_to_earn_extra_credit_point',
    'self_learning_test_difference_of_accuracy_between_stages',
    'self_learning_test_accuracy_extra_credit_points_for_each_stage',
    'self_learning_test_starting_normalized_ability_to_earn_credit_points',
    'self_learning_test_credit_points_earned_for_starting_normalized_ability',
    'self_learning_test_number_of_stages_to_earn_extra_credit_points',
    'self_learning_test_difference_of_normalized_ability_between_stages',
    'self_learning_test_ability_extra_credit_points_for_each_stage',
    'study_status_master',
    'min_no_question_per_study_progress',
    'max_no_question_per_study_progress',
    'question_window_size_of_learning_objective',

    // default credit points rules key
    'submission_on_time',
    'credit_points_of_accuracy',
    'credit_points_of_normalized_ability',

    // Custom Message
    'attempt_exam_restrict_notification_en',
    'attempt_exam_restrict_notification_ch',
    //AI-CAlibration
    'ai_calibration_percentage',
    'ai_calibration_minimum_student_accuracy',

    //Curriculum Year
    'current_curriculum_year',
    'exclude_ai_calibration_question_limit',
    'ai_calibration_included_question_seed_limit',
    'calibration_constant',
    'calibration_constant_percentile',

    // Game Configuration
    'planet_entry_color',
    'planet_castle_color',
    'planet_keys_color',
    'unexplored_planet_color',
    'general_planet_color',
    'planet_deduct_step_color',
    'planet_increase_step_color',
    'max_deduction_steps',
    'max_addition_steps',
    'game_introduction_video_url',
    'no_of_game_spot_keys',
    'game_music_file',

    // Custom layout color
    'super_admin_panel_color',
    'principal_panel_color',
    'panel_head_panel_color',
    'co_ordinator_panel_color',
    'teacher_panel_color',
    'student_panel_color',

    // Active Tab Color Set
    'super_admin_panel_active_color',
    'principal_panel_active_color',
    'panel_head_panel_active_color',
    'co_ordinator_panel_active_color',
    'teacher_panel_active_color',
    'student_panel_active_color',

    // Panels header background color
    'super_admin_header_color',
    'principal_header_color',
    'panel_head_header_color',
    'co_ordinator_header_color',
    'teacher_header_color',
    'student_header_color'
];

